version: "3.9"

services:
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/MLServer/mlruns
      - ./mlflow.db:/MLServer/mlflow.db
    networks:
      - monitoring

  mlflow-project:
    build:
      context: .
      dockerfile: Dockerfile.project
    container_name: mlflow-project
    depends_on:
      - mlflow-server
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
    working_dir: /MLProject
    volumes:
      - .:/MLProject
      - ./mlruns:/mlruns
    command: >
      bash -c "
      echo '‚è≥ Menunggu MLflow server aktif...';
      until curl -sf http://mlflow-server:5000; do
        echo 'Server belum siap, menunggu 5 detik...';
        sleep 5;
      done;

      echo '‚úÖ Server siap ‚Äî membuat eksperimen...';
      export MLFLOW_TRACKING_URI=http://mlflow-server:5000;
      python -c \"import mlflow; mlflow.set_experiment('california_housing_exp'); print('‚úÖ Experiment dibuat atau sudah ada.')\";

      echo 'üöÄ Menjalankan MLflow project...';
      mlflow run . --experiment-name 'california_housing_exp'
      "

    networks:
      - monitoring

  housing_app:
    build:
      context: .
      dockerfile: Dockerfile.project
    container_name: housing_app
    ports:
      - "8002:8002"
    environment:
      - PROMETHEUS_PORT=8002
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    depends_on:
      - mlflow-server
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    depends_on:
      - housing_app
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

volumes:
  grafana-storage:

networks:
  monitoring:
    driver: bridge
